version: '3.8'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./prisma/data:/var/lib/mysql
  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 root password;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc anonymous set public myminio/images;
      exit 0;
      "
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - 9090:9000
      - 33023:33023
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=password
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      /opt/bin/minio server /data --console-address :33023;
      "
    volumes:
      - ./minio:/data